### ISSUE TITLE
Warrior Atomic Surge Won't Go on LAS

### ISSUE THREAD

**Issue by Acemane** [ForgeUI/ForgeUI#186] opened 2015-10-11 17:03 UTC
The warrior's ability atomic surge will not go on the LAS when i have forge ui installed. I uninstalled forge ui then put atomic surge onto my LAS then i reinstalled forge and it removed atomic surge from the LAS again. In addition you can not add or subtract ability points from atomic surge or at least it does not show on forge ui.

**Comment by Toludin** [comment] 2015-10-12 05:59
Duplicate of #177.

**Closed by Toludin** 2015-10-12 05:59 UTC
Labels: duplicate
